### ISSUE TITLE
AppBar Closing Transition

### ISSUE THREAD

**Issue by alexknipfer** [knipferrc/stylized#1]
I did a little bit on my end for attempting to get the AppBar to transition when closing to the right in mobile view. Using `display: none` is what will prevent you from being able to make it transition back. Probably need to use `visibility: hidden` or adjust the opacity.

**Comment by knipferrc** [comment]
Im not sure I follow. Using visibility: hidden allows it to transition back when closing?

**Comment by knipferrc** [comment]
Not sure this animation is needed since most of the time the links will take you to a new route and the animation won't be seen anyway.
